### ISSUE TITLE
meanings for BC datacenter codes

### ISSUE THREAD

**Issue by bonds-git** [upsonp/dart#64]
The meaningful descriptions of the codes used should be displayed. The file shows at the mission level, data center, is simply a list of numbers with no indication of what they actually mean.

There are also a lot of codes available to a user which have 0 matches in BioChem...

[data_ctr_code](https://086gc-my.sharepoint.com/:i:/r/personal/shelley_bond_dfo-mpo_gc_ca/Documents/DART_Testing/Mission_DC_Code.PNG?csf=1&web=1&e=RqnILp)

**Patrick, do you have a process in place to sync with the BC lookup tables? Because there will need to be one**

**Comment by upsonp** [comment]
No, I don't currently have a process in place to sync with BC Lookup tables.

If you connect DART to the PTran BioChem account DART reads the tables (e.g BCDATATYPES, BCUNITS, BCMISSIONS) directly from oracle to get codes.

I assume the tables in BioChem on PTran are kept up-to-date with the actual BioChem database. If not we'll have to find a way to connect to the BioChem Database to pull codes from.

**Comment by upsonp** [comment]
I renamed this issue to be more specifically about datacenter codes. At the moment this is the only code used in DART before the application is connected to an oracle DB for BioChem staging.

We should long separate issues in the future as other biochem lookup tables are added to DART for performance/convenience.
