### ISSUE TITLE
Can't load CHL - no error message..?

### ISSUE THREAD

**Issue by bonds-git** [upsonp/dart#88]
It allows me to browse for this file (which is nice and maybe should be the case for all files....? But doesn't do anything with the file....

[CHL_Hud2021-185_final.xlsx](https://github.com/upsonp/dart/files/11735303/CHL_Hud2021-185_final.xlsx)

**Comment by bonds-git** [comment]
Never mind I found a file it did read... but there was a pop up window with 'warnings' about missing sample IDs. It would be nice maybe, and maybe it does this now, if the app generated a report with all errors and warnings for folks to use as a guide to clean up the issues....?

**Comment by upsonp** [comment]
Yes, at the top of the Samples page you'll see a yellow button "View Errors" (see image below), that lets you view the error report for currently loaded files in the system. You can also use the "downloadable reports" to download the error report.

Error reporting still needs some tweaking in places, especially when things go really really wrong, but I'm largely happy with it. 

I'll close this ticket.

![image](https://github.com/upsonp/dart/assets/3355126/550b51bc-a89c-48f3-82b3-433e94f1aacc)
